# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Indicador ICAv6 de adopción de IPv6
title_short: ICAv6
email: guillermo@lacnic.net
description: > # this means to ignore newlines until "baseurl:"
  Este sitio contiene el indicdor ICAv6 de adopción de IPv6
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://transfer-stats.labs.lacnic.net/Elisa-datos-abiertos/index.html"
url: "http://127.0.0.1:4001"
twitter_username: lacniclabs
github_username:  lacnic

# Build settings
markdown: kramdown
